acts/urls.py
from django.urls import path
from . import views, views_htmx

urlpatterns = [
    path('', views.acts, name='acts'),
    path('1/', views.tables_1, name='tables_1'),
    path('2/', views.tables_2, name='tables_2'),
    path('3/', views.tables_3, name='tables_3'),
    path('4/', views.tables_4, name='tables_4'),
    path('5/', views.tables_5, name='tables_5'),
    path('6/', views.tables_6, name='tables_6'),


    path('create/1', views.create_1, name='create_1'),
    path('create/2', views.create_2, name='create_2'),
    path('create/3', views.create_3, name='create_3'),
    path('create/4', views.create_4, name='create_4'),
    path('create/5', views.create_5, name='create_5'),
    path('create/6', views.create_6, name='create_6'),

    path('<int:pkey>/', views.act, name='act'),
    path('search', views.act_search),  # POST
    path('search/', views.act_search),  # GET


    path('tables/', views.tables, name='tables'),
    path('tables/first/<int:pkey>/', views.tables_first, name='tables_first'),
    path('tables/second/<int:pkey>/', views.tables_second, name='tables_second'),
    path('tables/first/table', views.tables, name='table_first'),
    path('tables/first/table', views.tables, name='table_second'),

    path('<int:pkey>/edit/', views_htmx.act_edit_form, name='act-edit-form'),
    path('<int:pkey>/edit/save', views_htmx.act_edit),
    path('status/', views_htmx.act_status),
    path('<int:pkey>/accept', views_htmx.accept_or_return_act, name='accept-or-return-act'),
]

scopus_pars/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include(('search.urls', 'searches'), namespace='search')),
    path('acts/', include(('acts.urls', 'acts'), namespace='acts')),
    path('accounts/', include(('accounts.urls', 'accounts'),  namespace='accounts')),
    path('__debug__/', include('debug_toolbar.urls')),
]

search/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.search, name='search'),
    path('new/<int:num>/<int:id>/', views.search_new, name='search_new'),
    path('articles/', views.search_articles, name='search_articles'),

    path('download/', views.download_xls, name='download'),

]

acts/forms.py
from django.forms import ModelForm
from django import forms
from .models import Table_1, Table_2, Table_3, Table_4, Table_5, Table_6


class Table_1_form(ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['title'].widget.attrs.update({'class': 'special'})

    file = forms.FileField(required=False)

    class Meta:
        model = Table_1
        fields = '__all__'
        exclude = ('act_processing', 'user', 'executer')

    def __init__(self, *args, **kwargs):
        custom_info = kwargs.pop('custom_info', None)  # get the custom info from the kwargs
        super().__init__(*args, **kwargs)
        if custom_info:
            self.fields['custom_field'].initial = custom_info.get('custom_field',
                                                                  '')  # set the initial value for the custom field

class Table_2_form(ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['title'].widget.attrs.update({'class': 'special'})

    file = forms.FileField(required=False)

    class Meta:
        model = Table_2
        fields = '__all__'
        exclude = ('user',)


class Table_3_form(ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['title'].widget.attrs.update({'class': 'special'})

    file = forms.FileField(required=False)

    class Meta:
        model = Table_3
        fields = '__all__'
        exclude = ('user',)


class Table_4_form(ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['title'].widget.attrs.update({'class': 'special'})

    file = forms.FileField(required=False)

    class Meta:
        model = Table_4
        fields = '__all__'
        exclude = ('user',)


class Table_5_form(ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['title'].widget.attrs.update({'class': 'special'})

    file = forms.FileField(required=False)

    class Meta:
        model = Table_5
        fields = '__all__'
        exclude = ('user',)


class Table_6_form(ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['title'].widget.attrs.update({'class': 'special'})

    file = forms.FileField(required=False)

    class Meta:
        model = Table_6
        fields = '__all__'
        exclude = ('user',)

acts/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.http import QueryDict
from .models import Table_1,Table_2,Table_3,Table_4,Table_5,Table_6
from .forms import Table_1_form,Table_2_form,Table_3_form,Table_4_form,Table_5_form,Table_6_form

def tables(request):

    return render(request, 'acts/tables.html', {})

def tables_first(request, pkey):
    if request.user.type == 'DISPATCHER':
        queryset = Table_1.objects.select_related('user').filter(user_id=pkey)
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'acts/tables_first.html', {'page_obj': page_obj})

def tables_second(request, pkey):
    if request.user.type == 'DISPATCHER':
        queryset = Table_1.objects.select_related('user').filter(user_id=pkey)
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'acts/tables_second.html', {'page_obj': page_obj})



def table_first(request):

    return render(request, 'acts/tables.html', {})


def table_second(request):

    return render(request, 'acts/tables.html', {})

















@login_required
def acts(request):
    if request.user.type == 'DISPATCHER':
        queryset = Table_1.objects.select_related('user').all().order_by('-date_updated')
    else:
        queryset = Table_1.objects.select_related('user').filter(
            user_id=request.user.id)  # request.session.get('_auth_user_id')
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'acts/act_list.html', {'page_obj': page_obj})

@login_required
def tables_1(request):
    if request.user.type == 'DISPATCHER':
        queryset = Table_1.objects.select_related('user').all().order_by('-date_updated')
    else:
        queryset = Table_1.objects.select_related('user').filter(
            user_id=request.user.id)  # request.session.get('_auth_user_id')
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'acts/tables_first.html', {'page_obj': page_obj})

@login_required
def tables_2(request):
    if request.user.type == 'DISPATCHER':
        queryset = Table_2.objects.select_related('user').all().order_by('-date_updated')
    else:
        queryset = Table_2.objects.select_related('user').filter(
            user_id=request.user.id)  # request.session.get('_auth_user_id')
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'acts/tables_second.html', {'page_obj': page_obj})

@login_required
def tables_3(request):
    if request.user.type == 'DISPATCHER':
        queryset = Table_3.objects.select_related('user').all().order_by('-date_updated')
    else:
        queryset = Table_3.objects.select_related('user').filter(
            user_id=request.user.id)  # request.session.get('_auth_user_id')
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'acts/tables_third.html', {'page_obj': page_obj})

@login_required
def tables_4(request):
    if request.user.type == 'DISPATCHER':
        queryset = Table_4.objects.select_related('user').all().order_by('-date_updated')
    else:
        queryset = Table_4.objects.select_related('user').filter(
            user_id=request.user.id)  # request.session.get('_auth_user_id')
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'acts/tables_fourth.html', {'page_obj': page_obj})

@login_required
def tables_5(request):
    if request.user.type == 'DISPATCHER':
        queryset = Table_5.objects.select_related('user').all().order_by('-date_updated')
    else:
        queryset = Table_5.objects.select_related('user').filter(
            user_id=request.user.id)  # request.session.get('_auth_user_id')
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'acts/tables_fifth.html', {'page_obj': page_obj})

@login_required
def tables_6(request):
    if request.user.type == 'DISPATCHER':
        queryset = Table_6.objects.select_related('user').all().order_by('-date_updated')
    else:
        queryset = Table_6.objects.select_related('user').filter(
            user_id=request.user.id)  # request.session.get('_auth_user_id')
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'acts/tables_sixth.html', {'page_obj': page_obj})


@login_required
def create_1(request):
    if request.method == 'GET':
        form = Table_1_form()
        message = "Журналы входящие в международные базы цитируемых журналов Web of Science и Scopus"
        return render(request, 'acts/create_act.html', {'form': form, 'message':message})

    elif request.method == 'POST':
        form = Table_1_form(request.POST, request.FILES)
        if form.is_valid():
            user = request.user.id
            form.instance.user_id = user
            form.save()
            return HttpResponseRedirect('http://127.0.0.1:8000/acts/')
        else:
            return render(request, 'acts/create_act.html', {'form': form})

@login_required
def create_2(request):
    if request.method == 'GET':
        form = Table_2_form()
        message = "Журналы входящие в международные базы цитируемых журналов Web of Science и Scopus"

        return render(request, 'acts/create_act_2.html', {'form': form, 'message':message})

    elif request.method == 'POST':
        form = Table_2_form(request.POST, request.FILES)
        if form.is_valid():
            user = request.user.id
            form.instance.user_id = user
            form.save()
            return HttpResponseRedirect('http://127.0.0.1:8000/acts/')
        else:
            return render(request, 'acts/create_act_2.html', {'form': form})

@login_required
def create_3(request):
    if request.method == 'GET':
        form = Table_3_form()
        message = "Журналы входящие в международные базы цитируемых журналов Web of Science и Scopus"
        return render(request, 'acts/create_act_3.html', {'form': form, 'message':message})

    elif request.method == 'POST':
        form = Table_3_form(request.POST, request.FILES)
        if form.is_valid():
            user = request.user.id
            form.instance.user_id = user
            form.save()
            return HttpResponseRedirect('http://127.0.0.1:8000/acts/')
        else:
            return render(request, 'acts/create_act_3.html', {'form': form})

@login_required
def create_4(request):
    if request.method == 'GET':
        form = Table_4_form()
        message = "Журналы входящие в международные базы цитируемых журналов Web of Science и Scopus"
        return render(request, 'acts/create_act_4.html', {'form': form, 'message':message})

    elif request.method == 'POST':
        form = Table_4_form(request.POST, request.FILES)
        if form.is_valid():
            user = request.user.id
            form.instance.user_id = user
            form.save()
            return HttpResponseRedirect('http://127.0.0.1:8000/acts/')
        else:
            return render(request, 'acts/create_act_4.html', {'form': form})

@login_required
def create_5(request):
    if request.method == 'GET':
        form = Table_5_form()
        message = "Журналы входящие в международные базы цитируемых журналов Web of Science и Scopus"
        return render(request, 'acts/create_act_5.html', {'form': form, 'message':message})

    elif request.method == 'POST':
        form = Table_5_form(request.POST, request.FILES)
        if form.is_valid():
            user = request.user.id
            form.instance.user_id = user
            form.save()
            return HttpResponseRedirect('http://127.0.0.1:8000/acts/')
        else:
            return render(request, 'acts/create_act_5.html', {'form': form})

@login_required
def create_6(request):
    if request.method == 'GET':
        form = Table_6_form()
        message = "Журналы входящие в международные базы цитируемых журналов Web of Science и Scopus"
        return render(request, 'acts/create_act_6.html', {'form': form, 'message':message})

    elif request.method == 'POST':
        form = Table_6_form(request.POST, request.FILES)
        if form.is_valid():
            user = request.user.id
            form.instance.user_id = user
            form.save()
            return HttpResponseRedirect('http://127.0.0.1:8000/acts/')
        else:
            return render(request, 'acts/create_act_6.html', {'form': form})


@login_required
def act(request, pkey):
    queryset = get_object_or_404(Table_1, pk=pkey)
    if request.user.type == 'DISPATCHER' or request.user.id == queryset.user_id:
        return render(request, 'acts/act.html', {'act': queryset})
    else:
        return render(request, 'no_access.html')


def act_search(request):
    if request.user.type == 'DISPATCHER':
        if request.method == 'POST':
            # any orm injections?
            search = request.POST['search']
            acts = Table_1.objects.all()
            queryset = [act for act in acts if (
                    (search.lower() in act.title.lower())
                    or
                    (search.lower() in act.adress.lower())
                    or
                    (search.lower() in act.text.lower()))
                        ]

templates/acts/act_list.html
<!DOCTYPE html>
{% extends "../base.html" %}
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">


  <style>
    #center {
      width: 1700px;
      height: 750px;
      border: 5px solid #333;
      border-top-width: 0px;
      border-bottom-right-radius: 25px;
      border-bottom-left-radius: 25px;
      background-image: linear-gradient(rgb(255, 255, 255), rgb(255, 255, 255), rgb(255, 255, 255),rgb(255, 255, 255),rgb(255, 255, 255),rgb(173, 252, 166));
    }
    
    .row{
      margin-top: 20px;

    }
  </style>

</head>
    {% block content %}

<!-- HTMX -->
<script src="https://unpkg.com/htmx.org@1.6.1"></script>


 <hr>

<button hx-get="{% url 'acts:tables_1' %}" hx-target="#body" hx-swap="outerHTML">Журналы входящие в международные базы цитируемых журналов Web of Science и Scopus</button>
<button hx-get="{% url 'acts:tables_2' %}" hx-target="#body" hx-swap="outerHTML">Журналы входящие в Рецензирумые зарубежные журналы (РИНЦ)</button>
<button hx-get="{% url 'acts:tables_3' %}" hx-target="#body" hx-swap="outerHTML">Журналы входящие в Рецензирумые зарубежные журналы рекомендуемые КОКСНВО</button>
<button hx-get="{% url 'acts:tables_4' %}" hx-target="#body" hx-swap="outerHTML">Статьи опубликованные в сборниках конференции</button>
<button hx-get="{% url 'acts:tables_5' %}" hx-target="#body" hx-swap="outerHTML">Свидетельство о государственной регистрации прав на объект авторского права</button>
<button hx-get="{% url 'acts:tables_6' %}" hx-target="#body" hx-swap="outerHTML">Участие в научных проектах </button>

<br>
<br>



 <div id="body">
<a class="button" href="{% url 'acts:create_1' %}">Добавить</a>

<table id="acts">
  <thead>
    <tr>
      <th>Название статьи</th>
      <th>Соавторы</th>
      <th>Тип автора</th>
      <th>Количество авторов</th>
      <th>Название журнала, номер, год выпуска </th>
      <th>Процентиль  (1..100 по Scopus) или квартиль (Q1..Q4 по WoS)</th>
      <th>DOI статьи</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in page_obj %}
    <tr>
      <td>{{obj.title}}</td>
      <td>{{obj.co_creators}}</td>
      <td>{{obj.author_type}}</td>
      <td>{{obj.number_of_authors}}</td>
      <td>{{obj.journal_title}}</td>
      <td>{{obj.percentile}}</td>
      <td>{{obj.url}}</td>
      <td>{{obj.file}}</td>
    </tr>
    {% endfor %}
  </tbody>
  <script src="https://unpkg.com/htmx.org@1.6.1"></script>

</table>



{% if page_obj.has_previous %}
<a href="?page=1">&laquo First</a>
<a href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">next</a>
<a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
{% endif %}

</div>

  {% endblock %}



</html>

templates/acts/create_act.html
<!DOCTYPE html>
{% extends "../base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Act</title>
    <script src="https://unpkg.com/htmx.org@1.6.1"></script>

</head>
<body>
    {% block content %}
{{message}}


    <form id="data" method="post" action="{% url 'acts:create_1' %}" enctype="multipart/form-data">
        {% csrf_token %}
    
        {{form.as_ul}}
    
        <input class="btn btn-primary" type="submit"/>
        <input type="hidden" name="next" value="{{ next }}" />

    </form>

 <div id="articles">

 </div>
    <script src="https://unpkg.com/htmx.org@1.6.1"></script>

<br>
<br>

    scopus id
    <form hx-post="{% url 'search:search_articles' %}" hx-target="#articles" hx-swap="outerHTML">
    {% csrf_token %}
    <input type="text" name="query" placeholder="ID">


    <button type="submit">Search</button>
</form>
<script src="https://unpkg.com/htmx.org@1.6.1"></script>
    {% endblock %}
</body>
</html>

templates/acts/create_act_2.html
<!DOCTYPE html>
{% extends "../base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Act</title>
</head>
<body>
    {% block content %}
{{message}}
    <form method="post" action="{% url 'acts:create_2' %}" enctype="multipart/form-data">
        {% csrf_token %}
    
        {{form.as_ul}}
    
        <input class="btn btn-primary" type="submit"/>
        <input type="hidden" name="next" value="{{ next }}" />

    </form>

    {% endblock %}
</body>
</html>

templates/acts/create_act_3.html
<!DOCTYPE html>
{% extends "../base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Act</title>
</head>
<body>
    {% block content %}
{{message}}
    <form method="post" action="{% url 'acts:create_3' %}" enctype="multipart/form-data">
        {% csrf_token %}
    
        {{form.as_ul}}
    
        <input class="btn btn-primary" type="submit"/>
        <input type="hidden" name="next" value="{{ next }}" />

    </form>

    {% endblock %}
</body>
</html>

templates/acts/create_act_4.html
<!DOCTYPE html>
{% extends "../base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Act</title>
</head>
<body>
    {% block content %}
{{message}}
    <form method="post" action="{% url 'acts:create_4' %}" enctype="multipart/form-data">
        {% csrf_token %}
    
        {{form.as_ul}}
    
        <input class="btn btn-primary" type="submit"/>
        <input type="hidden" name="next" value="{{ next }}" />

    </form>

    {% endblock %}
</body>
</html>

templates/acts/create_act_5.html
<!DOCTYPE html>
{% extends "../base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Act</title>
</head>
<body>
    {% block content %}
{{message}}
    <form method="post" action="{% url 'acts:create_5' %}" enctype="multipart/form-data">
        {% csrf_token %}
    
        {{form.as_ul}}
    
        <input class="btn btn-primary" type="submit"/>
        <input type="hidden" name="next" value="{{ next }}" />

    </form>

    {% endblock %}
</body>
</html>

templates/acts/create_act_6.html
<!DOCTYPE html>
{% extends "../base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Act</title>
</head>
<body>
    {% block content %}
{{message}}
    <form method="post" action="{% url 'acts:create_6' %}" enctype="multipart/form-data">
        {% csrf_token %}
    
        {{form.as_ul}}
    
        <input class="btn btn-primary" type="submit"/>
        <input type="hidden" name="next" value="{{ next }}" />

    </form>

    {% endblock %}
</body>
</html>

templates/acts/tables.html
<!DOCTYPE html>
{% extends '../base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://unpkg.com/htmx.org@1.6.1"></script>
</head>
<body>
{% block content %}

Профиль пользователя: {{username}}
<br>
<br>

 <a href="{% url 'acts:tables' %}">Все таблицы</a>
 <button hx-get="{% url 'acts:tables_first' pkey=pkey %}" hx-target="#body" hx-swap="outerHTML">Первая таблица</button>
 <button hx-get="{% url 'acts:tables_second' pkey=pkey %}" hx-target="#body" hx-swap="outerHTML">Вторая таблица</button>


<div id="body">

<table>
    <thead>
      <tr>
        <th>№</th>
        <th>User name</th>
        <th>Title</th>
        <th>Adress</th>
        <th>Act type</th>
        <th>Act text</th>
        <th>Date created</th>
        <th>Date updated</th>
         <th>Act processing</th>
         <th>Do untill</th>
      </tr>
    </thead>
    <tbody>
     {% for obj in page_obj %}
    <tr>
      <td> {{ forloop.counter }}</td>
      <td>{{obj.user}}</td>
      <td>{{obj.title}}</td>
      <td>{{obj.adress}}</td>
      <td>{{obj.act_type}}</td>
      <td>{{obj.date_created}}</td>
      <td>{{obj.date_updated}}</td>
      <td><a href="http://127.0.0.1:8000/acts/{{obj.id}}">Смотреть заявку</a></td>
      <td>
       </td>

    </tr>
    {% endfor %}

    </tbody>
  </table>

</div>
 <script src="https://unpkg.com/htmx.org@1.6.1"></script>
{% endblock %}
</body>
</html>

templates/acts/tables_fifth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Пятая таблица</title>
</head>
<body>


<div id="body">
<a class="button" href="{% url 'acts:create_5' %}">Добавить</a>
<table id="acts">
  <thead>
    <tr>
      <th>User name</th>
      <th>Title</th>
      <th>Adress</th>
      <th>Act type</th>
      <th>Date created</th>
      <th>Date updated</th>
      <th>Url</th>
      {% if request.user.type == 'DISPATCHER' %}
      <th>Accept</th>
      {% else %}
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for obj in page_obj %}
    <tr>
      <td>{{obj.user}}</td>
      <td>{{obj.title}}</td>
      <td>{{obj.adress}}</td>
      <td>{{obj.act_type}}</td>
      <td>{{obj.date_created}}</td>
      <td>{{obj.date_updated}}</td>
      <td><a href="http://127.0.0.1:8000/acts/{{obj.id}}">Смотреть таблицу</a></td>
      <td>
       </td>

    </tr>
    {% endfor %}
  </tbody>
  <script src="https://unpkg.com/htmx.org@1.6.1"></script>

</table>



{% if page_obj.has_previous %}
<a href="?page=1">&laquo First</a>
<a href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">next</a>
<a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
{% endif %}





  </body>


</body>
</html>

templates/acts/tables_first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Первая таблица</title>
</head>
<body>


<div id="body">
<a class="button" href="{% url 'acts:create_1' %}">Добавить</a>
<table id="acts">
  <thead>
    <tr>
      <th>Название статьи</th>
      <th>Соавторы</th>
      <th>Тип автора</th>
      <th>Количество авторов</th>
      <th>Название журнала, номер, год выпуска </th>
      <th>Процентиль  (1..100 по Scopus) или квартиль (Q1..Q4 по WoS)</th>
      <th>DOI статьи</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in page_obj %}
    <tr>
      <td>{{obj.title}}</td>
      <td>{{obj.co_creators}}</td>
      <td>{{obj.author_type}}</td>
      <td>{{obj.number_of_authors}}</td>
      <td>{{obj.journal_title}}</td>
      <td>{{obj.percentile}}</td>
      <td>{{obj.url}}</td>
      <td>{{obj.file}}</td>
    </tr>
    {% endfor %}
  </tbody>
  <script src="https://unpkg.com/htmx.org@1.6.1"></script>

</table>



{% if page_obj.has_previous %}
<a href="?page=1">&laquo First</a>
<a href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">next</a>
<a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
{% endif %}





</div>


</body>
</html>