accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('register/', views.register, name='register'),
    path('profile/',views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('login/', views.BBLoginView.as_view(), name='login'),
    path('logout/', views.BBLogoutView.as_view(), name='logout'),
    path('users/', views.users, name='users'),
    path('user/<int:pkey>',views.user, name='user'),
]

acts/urls.py
from django.urls import path
from . import views, views_htmx

urlpatterns = [
    path('', views.acts, name='acts'),
    path('1/', views.tables_1, name='tables_1'),
    path('2/', views.tables_2, name='tables_2'),
    path('3/', views.tables_3, name='tables_3'),
    path('4/', views.tables_4, name='tables_4'),
    path('5/', views.tables_5, name='tables_5'),
    path('6/', views.tables_6, name='tables_6'),


    path('create/1', views.create_1, name='create_1'),
    path('create/2', views.create_2, name='create_2'),
    path('create/3', views.create_3, name='create_3'),
    path('create/4', views.create_4, name='create_4'),
    path('create/5', views.create_5, name='create_5'),
    path('create/6', views.create_6, name='create_6'),

    path('<int:pkey>/', views.act, name='act'),
    path('search', views.act_search),  # POST
    path('search/', views.act_search),  # GET


    path('tables/', views.tables, name='tables'),
    path('tables/first/<int:pkey>/', views.tables_first, name='tables_first'),
    path('tables/second/<int:pkey>/', views.tables_second, name='tables_second'),
    path('tables/first/table', views.tables, name='table_first'),
    path('tables/first/table', views.tables, name='table_second'),

    path('<int:pkey>/edit/', views_htmx.act_edit_form, name='act-edit-form'),
    path('<int:pkey>/edit/save', views_htmx.act_edit),
    path('status/', views_htmx.act_status),
    path('<int:pkey>/accept', views_htmx.accept_or_return_act, name='accept-or-return-act'),
]

scopus_pars/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include(('search.urls', 'searches'), namespace='search')),
    path('acts/', include(('acts.urls', 'acts'), namespace='acts')),
    path('accounts/', include(('accounts.urls', 'accounts'),  namespace='accounts')),
    path('__debug__/', include('debug_toolbar.urls')),
]

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils.translation import gettext_lazy as _


class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have a username')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.type = 'DISPATCHER'
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    date_updated = models.DateTimeField(auto_now=True)

    class Types(models.TextChoices):
        USER = "USER", "User"
        DISPATCHER = "DISPATCHER", "Dispatcher"
        DEPARTMENT_HEAD = "DEPARTMENT_HEAD", "Department_head"
        EXECUTOR = "EXECUTOR", "Executor"

    base_type = Types.USER
    type = models.CharField(
        _("Type"), max_length=50, choices=Types.choices, default=base_type
    )

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = MyAccountManager()

    # class Meta:
    # indexes = [models.Index(fields=['fieldname1', 'fieldname1']), ]

    def __str__(self):
        return self.username

    # For checking permissions. to keep it simple all admin have ALL permissons
    def has_perm(self, perm, obj=None):
        return self.is_admin

    # Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    def has_module_perms(self, app_label):
        return True

    def save(self, *args, **kwargs):
        if not self.id:
            self.type = self.base_type
        return super().save(*args, **kwargs)


class UserManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=Account.Types.USER)


class User(Account):
    base_type = Account.Types.USER
    objects = UserManager()

    class Meta:
        proxy = True

    def whisper(self):
        return "i'm user"


class DispatcherManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=Account.Types.DISPATCHER)


class Dispatcher(Account):
    base_type = Account.Types.DISPATCHER
    objects = DispatcherManager()

    class Meta:
        proxy = True

    def whisper(self):
        return "i'm dispatcher"


class DepartmentHeadManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=Account.Types.DEPARTMENT_HEAD)


class DepartmentHead(Account):
    base_type = Account.Types.DEPARTMENT_HEAD
    objects = DepartmentHeadManager()

    class Meta:
        proxy = True

    def whisper(self):
        return "i'm department head"


class ExecutorManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=Account.Types.EXECUTOR)


class Executor(Account):
    base_type = Account.Types.EXECUTOR
    objects = ExecutorManager()

    class Meta:
        proxy = True

    def whisper(self):
        return "i'm executor"

# class ExecutorMore(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     gadgets = models.TextField()

accounts/forms.py
from django import forms
from .models import Account


from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')

    class Meta:
        model = Account
        fields = ('email', 'username', 'password1', 'password2',)

accounts/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import RegistrationForm
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Account
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator
from acts.models import Table_1

@login_required
def profile(request):
    user_id = request.user.id
    queryset = Account.objects.get(id=user_id)  # get_object_or_404(Account, pk=user_id)
    return render(request, 'accounts/profile.html', {'profile': queryset})


def register(request):
    if request.method == 'GET':
        form = RegistrationForm()
        return render(request, 'accounts/register.html', {'form': form})

    elif request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ('успешная регистрация'))
            return HttpResponseRedirect('../../')
        else:
            return render(request, 'accounts/register.html', {'form': form})


class BBLoginView(LoginView):
    template_name = 'accounts/login.html'


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'accounts/logout.html'



@login_required
def users(request):
    if request.user.type == 'DISPATCHER':
        queryset = Account.objects.all().order_by('-date_updated')
        paginator = Paginator(queryset, 10)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'accounts/users.html', {"page_obj": page_obj})

@login_required
def user(request, pkey):
    if request.user.type == 'DISPATCHER':
        queryset = Table_1.objects.select_related('user').filter(user_id=pkey).order_by('date_updated')
        profile = Account.objects.get(id=pkey)
        username = profile.username
        paginator = Paginator(queryset, 10)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'acts/tables.html', {"page_obj": page_obj, "pkey": pkey, "username": username})

templates/accounts/login.html
<!DOCTYPE html>
{% extends "../base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


{% block title %}Вход{% endblock %}

    {% block content %}

{% if form.errors %}
  <p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
  {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed, please login with an account that has access.</p>
  {% else %}
    <p>Please login to see this page.</p>
  {% endif %}
{% endif %}

<form method="post" action="{% url 'accounts:login' %}">
{% csrf_token %}
<table>

<tr>
  <td>{{ form.username.label_tag }}</td>
  <td>{{ form.username }}</td>
</tr>

<tr>
  <td>{{ form.password.label_tag }}</td>
  <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>




    {% endblock %}
</body>
</html>

templates/accounts/logout.html
<!DOCTYPE html>
{% extends "../base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

{% block title %}Выход{% endblock %}
{% block content %}
<h2 >Выход</h2>
Вы успешно вышли с сайта.
{% endblock %}


</body>
</html>

templates/accounts/profile.html
<!DOCTYPE html>
{% extends "../base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

{% block content %}

<h4>Профиль</h4><br>
<p>username: {{ profile.username }}</p>
<p>admin: {{ profile.is_admin }}</p>
<p>type: {{ profile.type }}</p>


{% endblock %}

</body>
</html>

templates/accounts/register.html
<!DOCTYPE html>
{% extends "../base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Account</title>
</head>
<body>
    {% block content %}
    <form method="post" action="{% url 'accounts:register' %}">
        {% csrf_token %}
    
        {{form.as_ul}}
    
        <input class="btn btn-primary" type="submit"/>
        <input type="hidden" name="next" value="{{ next }}" />

    </form>
    {% endblock %}
</body>
</html>

templates/accounts/users.html
<!DOCTYPE html>
{% extends "../base.html" %}
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">


  <style>
    #center {
      width: 1700px;
      height: 750px;
      border: 5px solid #333;
      border-top-width: 0px;
      border-bottom-right-radius: 25px;
      border-bottom-left-radius: 25px;
      background-image: linear-gradient(rgb(255, 255, 255), rgb(255, 255, 255), rgb(255, 255, 255),rgb(255, 255, 255),rgb(255, 255, 255),rgb(173, 252, 166));
    }

    .row{
      margin-top: 20px;

    }
  </style>

</head>
    {% block content %}

<!-- HTMX -->
<script src="https://unpkg.com/htmx.org@1.6.1"></script>


<!-- {% if request.user.type == "DISPATCHER" %} -->
<!--
<form hx-post="search" hx-target="#body" hx-swap="outerHTML">
    {% csrf_token %}
    <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Поиск" name="search">
    <input class="btn btn-primary" type="submit" value="Найти"/>
</form>  -->

<br>

<!-- <div>
  <label >Сортировать по:</label>
  <select name="make" hx-get="/models" hx-target="#models" hx-indicator=".htmx-indicator">
    <option value="audi">Дате изменения заявки</option>
    <option value="toyota">Дате создания заявки</option>
  </select>
</div> -->

<br>
<!--
<div>
  <label >Заявки:</label>
  <select name="status" hx-get="status" hx-target="#body" hx-swap="outerHTML" hx-indicator=".htmx-indicator">
    <option value="all">Все</option>
    <option value="completed">Выполненные</option>
    <option value="uncompleted">Не выполненные</option>
    <option value="new">Новые</option>
    <option value="expired">Просроченные</option>
  </select>
</div> -->


{% endif %}


 <hr>

 <div id="body">

<table id="profiles">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>date_joined</th>
      <th>last_login</th>
      <th>is_staff</th>
      <th>type</th>
      <th>last update</th>
      <th>Url</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in page_obj %}
    <tr>
      <td>{{obj.username}}</td>
      <td>{{obj.email}}</td>
      <td>{{obj.date_joined}}</td>
      <td>{{obj.last_login}}</td>
      <td>{{obj.is_staff}}</td>
      <td>{{obj.type}}</td>
      <td>{{obj.date_updated}}</td>
      <td><a href="{% url 'accounts:user' pkey=obj.id %}">Открыть работы</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>





{% if page_obj.has_previous %}
<a href="?page=1">&laquo First</a>
<a href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">next</a>
<a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
{% endif %}

<div>

  {% endblock %}

  </body>

</html>