accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('register/', views.register, name='register'),
    path('profile/',views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('login/', views.BBLoginView.as_view(), name='login'),
    path('logout/', views.BBLogoutView.as_view(), name='logout'),
    path('users/', views.users, name='users'),
    path('user/<int:pkey>',views.user, name='user'),
]

acts/urls.py
from django.urls import path
from . import views, views_htmx

urlpatterns = [
    path('', views.acts, name='acts'),
    path('1/', views.tables_1, name='tables_1'),
    path('2/', views.tables_2, name='tables_2'),
    path('3/', views.tables_3, name='tables_3'),
    path('4/', views.tables_4, name='tables_4'),
    path('5/', views.tables_5, name='tables_5'),
    path('6/', views.tables_6, name='tables_6'),


    path('create/1', views.create_1, name='create_1'),
    path('create/2', views.create_2, name='create_2'),
    path('create/3', views.create_3, name='create_3'),
    path('create/4', views.create_4, name='create_4'),
    path('create/5', views.create_5, name='create_5'),
    path('create/6', views.create_6, name='create_6'),

    path('<int:pkey>/', views.act, name='act'),
    path('search', views.act_search),  # POST
    path('search/', views.act_search),  # GET


    path('tables/', views.tables, name='tables'),
    path('tables/first/<int:pkey>/', views.tables_first, name='tables_first'),
    path('tables/second/<int:pkey>/', views.tables_second, name='tables_second'),
    path('tables/first/table', views.tables, name='table_first'),
    path('tables/first/table', views.tables, name='table_second'),

    path('<int:pkey>/edit/', views_htmx.act_edit_form, name='act-edit-form'),
    path('<int:pkey>/edit/save', views_htmx.act_edit),
    path('status/', views_htmx.act_status),
    path('<int:pkey>/accept', views_htmx.accept_or_return_act, name='accept-or-return-act'),
]

scopus_pars/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include(('search.urls', 'searches'), namespace='search')),
    path('acts/', include(('acts.urls', 'acts'), namespace='acts')),
    path('accounts/', include(('accounts.urls', 'accounts'),  namespace='accounts')),
    path('__debug__/', include('debug_toolbar.urls')),
]

search/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.search, name='search'),
    path('new/<int:num>/<int:id>/', views.search_new, name='search_new'),
    path('articles/', views.search_articles, name='search_articles'),

    path('download/', views.download_xls, name='download'),

]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render

import requests
import openpyxl

import os
from django.http import FileResponse

import mimetypes

from acts.forms import Table_1_form


def get_publication_info(url):
    response = requests.get(url)
    publications_info = []
    if response.status_code == 200:
        data = response.json()
        entries = data.get("search-results").get("entry")
        for entry in entries:
            title = entry.get("dc:title")
            creator = entry.get("dc:creator")
            publicationName = entry.get("prism:publicationName")
            doi = entry.get("prism:doi")
            try:
                affil_name = entry["affiliation"][0]["affilname"]
                affiliation_city = entry["affiliation"][0]["affiliation-city"]
                affiliation_country = entry["affiliation"][0]["affiliation-country"]
            except Exception as e:
                pass
            articles_info = {
                "title": title,
                "creator": creator,
                "publicationName": publicationName,
                "affil_name": affil_name,
                "affiliation_city": affiliation_city,
                "affiliation_country": affiliation_country,
                "doi": doi
            }

            publications_info.append(articles_info)
    else:
        print("Request failed with status code", response.status_code)

    return publications_info


def create_exl(id):
    # author_search_url = f"https://api.elsevier.com/content/search/author?query=AUTHLASTNAME(%22{lastname}%22)%20AND%20AUTHFIRST(%22{firstname}%22)&apiKey=f0097b56b4ed057a6d01f4a20620c3d0"
    #
    # response = requests.get(author_search_url)
    # if response.status_code == 200:
    #     data = response.json()
    #     id = data.get("search-results").get("entry")[0].get("dc:identifier")
    #     id = id.replace('AUTHOR_ID:', '')

    # AUID = int(input())
    # url = f"https://api.elsevier.com/content/search/scopus?query=AU-ID({AUID})&apiKey=f0097b56b4ed057a6d01f4a20620c3d0"
    url = f"https://api.elsevier.com/content/search/scopus?query=AU-ID({id})&apiKey=f0097b56b4ed057a6d01f4a20620c3d0"
    # url = f"https://api.elsevier.com/content/search/scopus?query=AU-ID(57209645760)&apiKey=f0097b56b4ed057a6d01f4a20620c3d0"
    publication_info = get_publication_info(url)

    for i in range(len(publication_info)):
        print(publication_info[i].get("title"))
        print(publication_info[i].get("creator"))
        print(publication_info[i].get("publicationName"))
        print(publication_info[i].get("affil_name"))
        print(publication_info[i].get("affiliation_city"))
        print(publication_info[i].get("affiliation_country"))
        print("--------------------------")

    # Open an existing Excel file or create a new one
    wb = openpyxl.Workbook()

    # Create two new sheets
    sheet1 = wb.create_sheet("Sheet1")
    sheet2 = wb.create_sheet("Sheet2")

    # Select the active sheet (Sheet1)
    sheet = wb.active

    # Write headers to the active sheet
    sheet['A1'] = 'Название статьи'
    for i in range(len(publication_info)):
        sheet[f'A{i + 2}'] = publication_info[i].get("title")
    sheet['B1'] = 'Автор'
    for i in range(len(publication_info)):
        sheet[f'B{i + 2}'] = publication_info[i].get("creator")
    sheet['C1'] = 'Журнал'
    for i in range(len(publication_info)):
        sheet[f'C{i + 2}'] = publication_info[i].get("publicationName")
    sheet['D1'] = 'Университет'
    for i in range(len(publication_info)):
        sheet[f'D{i + 2}'] = publication_info[i].get("affil_name")
    sheet['E1'] = 'Город'
    for i in range(len(publication_info)):
        sheet[f'E{i + 2}'] = publication_info[i].get("affiliation_city")
    sheet['F1'] = 'Страна'
    for i in range(len(publication_info)):
        sheet[f'F{i + 2}'] = publication_info[i].get("affiliation_country")
    sheet['G1'] = 'Оттиск прикрепить'
    sheet['H1'] = 'Количество цитирование Скопус/ веб оф сайнс'
    sheet['I1'] = 'Тип автора'
    sheet['J1'] = 'Количество авторов'
    sheet['D2'] = 'Поиск на сайте или или Название сайте ДА/нет'
    sheet['E2'] = 'Поиск на сайте или или Название сайте ДА/нет'
    sheet['F2'] = 'Поиск на сайте или или Название сайте ДА/нет'
    sheet['I2'] = 'Первый автор Автор кореспондент Соавтор (низбадающий список)'

    sheet = sheet1
    sheet['A1'] = 'Название Свидетельства'
    sheet['B1'] = 'Данные о свидетельстве'
    sheet['C1'] = 'авторы'
    sheet['D1'] = 'Прикрепить копию пдф'

    sheet = sheet2
    sheet['A1'] = 'Название '
    sheet['B1'] = 'Год выпуска, издательство.'
    sheet['C1'] = 'Количество страниц'
    sheet['C1'] = 'Прикрепить оттиск пдф'
    sheet['A2'] = 'Чтение с вложеноого файла автоматический'
    sheet['B2'] = 'Чтение с вложеноого файла автоматический'

    # Save the changes to the Excel file
    wb.save('media/data.xlsx')
    return publication_info


def search(request):
    if request.method == 'GET':
        return render(request, 'search.html', {})

    elif request.method == 'POST':
        id = request.POST['query']

        info = create_exl(id)

        return render(request, 'search_results.html', {'query': info})


def search_new(request, id, num):
    if request.method == 'POST':


        info = create_exl(id)

        form = Table_1_form(initial={'title': info[num-1].get("title"), 'journal_title': info[num-1].get("publicationName"),
                                     'url': info[num-1].get("doi"), 'author_first': info[num-1].get("creator")})

        return render(request, 'search_results_articles.html', {'form': form})


def search_articles(request):
    if request.method == 'POST':
        id = request.POST['query']

        info = create_exl(id)

        result_len = len(info)

        return render(request, 'search_results_new.html', {'id': id, 'page_obj': info})


def download_xls(request):
    # Set the path to the XLSX file on disk
    filepath = 'media/data.xlsx'

    # Determine the MIME type based on the file extension
    mimetype, _ = mimetypes.guess_type(filepath)

    # Set the Content-Type header to the MIME type
    response = FileResponse(open(filepath, 'rb'), content_type=mimetype)

    # Set the Content-Disposition header to force download
    response['Content-Disposition'] = 'attachment; filename="%s"' % os.path.basename(filepath)

    return response

templates/base.html
<!DOCTYPE html>

{% load static %}
<html>
<head>

  
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #333;
  
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
  
  
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #4CAF50;
  color: white;
}



</style>
</head>
<body>
  
<div class="topnav">
  <a class="active" href="http://127.0.0.1:8000">Home</a>

  <a href="{% url 'search:search' %}">Поиск</a>
  <a href="{% url 'accounts:users' %}">Пользователи</a>
  <a href="{% url 'acts:acts' %}">Таблицы</a>
  <a href="{% url 'accounts:profile' %}">Профиль</a>
  {% if user.is_authenticated %}<a href="{% url 'accounts:logout' %}">Выход</a>
  {% else %}
  <a href="{% url 'accounts:register' %}">Регистрация</a>
  <a href="{% url 'accounts:login' %}">Вход</a>
  {% endif %}




</div>

<hr>
  {% block content %}
  {% endblock %}




</body>
</html>

templates/no_access.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    {% block title %}нету доступа{% endblock %}
    {% block content %}

 
    нет доступа




    {% endblock %}

</body>
</html>

templates/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <title>Scopus Data</title>
</head>
<body>
    <div class="cr__outer">
        <div class="cr__inner">
            <div class="cr">
                Julian Zaharchenko
            </div>
            <div class="cr">
                Kairbekov Adil
            </div>
            <div class="cr">
                Alimbetov Daulet
            </div>
            <div class="cr">
                Kairzhan Iliyas
            </div>
            <div class="cr">
                Haviz Ablaykhan
            </div>
            <div class="cr">
                Kakimov Nurbol
            </div>
            <div class="cr">
                Zhumanalin Rahat
            </div>
        </div>
    </div>
    <header class="header">
        <div class="container">
            <div class="header__inner">
                <img class="logo" src="{% static 'assets/img/logo.png' %}" alt="logo">
                <button class="cr-btn">
                    Creators
                </button>
            </div>
        </div>
    </header>
    <form class="form" method="post">
    {% csrf_token %}
    <input type="text" name="query" placeholder="Lastname">
    <input type="text" name="another_query" placeholder="Firstname">

    <button type="submit">Search</button>
</form>

<script src="{% static 'app.js' %}"></script>
</body>
</html>

templates/search_results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Scopus Data</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
  </head>
  <body>

    <div class="row">
      <div class="col">
        <div class="title">TITLE</div>
        {% for item in query %}
        <div class="text">
          {{ item.title }}
        </div>
        {% endfor %}
      </div>

      <div class="col">
        <div class="title">CREATOR</div>
        {% for item in query %}
        <div class="text">
          {{ item.creator }}
        </div>
        {% endfor %}

      </div>
      <div class="col">
        <div class="title">JOURNAL</div>
        {% for item in query %}
        <div class="text">
          {{ item.publicationName }}
        </div>
        {% endfor %}
      </div>


    </div>


    <div class="row">
      <div class="col">
        <div class="title">affiliation_city</div>
        {% for item in query %}
        <div class="text">
          {{ item.affiliation_city }}
        </div>
        {% endfor %}
      </div>

      <div class="col">
        <div class="title">affiliation_country</div>
        {% for item in query %}
        <div class="text">
          {{ item.affiliation_country }}
        </div>
        {% endfor %}
      </div>

      <div class="col">
        <div class="title">JOURNAL</div>
        {% for item in query %}
        <div class="text">
          {{ item.publicationName }}
        </div>
        {% endfor %}
      </div>

    </div>

    <a href="{% url 'search:download' %}">
  <button>Download Excel file</button>
</a>

    <script src="{% static 'app.js' %}"></script>
  </body>
</html>

templates/search_results_articles.html
<form id="data" method="post" action="{% url 'acts:create_1' %}" enctype="multipart/form-data">
        {% csrf_token %}

        {{form.as_ul}}

        <input class="btn btn-primary" type="submit"/>
        <input type="hidden" name="next" value="{{ next }}" />

    </form>

templates/search_results_new.html
{% for obj in page_obj %}
<button hx-post="{% url 'search:search_new' num=forloop.counter id=id %}" hx-target="#data" hx-swap="outerHTML" hx-headers='{ "X-CSRFToken": "{{ csrf_token }}" }'>{{obj.title}}</button>
<br>
{% endfor %}